name: T.S. Bateman
favicon: null
layout_spectrum: 0.17044314881786704
typography_spectrum: 0.6378749632276595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#504e59'
    - '#e0e1dc'
    - '#878183'
    - '#111c32'
    - '#c7c2bf'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.9021457307972014
  rhythmicContrast: 0
purpose: []
